language: objective-c

before_install:
  - brew install yarn
  - gem install bundler
  - bundle update

before_script:
  - git clone https://github.com/artsy/emission.git fastlane/emission
  - cd fastlane/emission && npm install
  - git pull origin fastlane_match 
  - cd Example && pod install
  - cd ../../..

script:

  - bundle exec fastlane ship
